name: package-test
on:  
  push:    
    branches:      
        - main 
    
jobs:  
  publish-gpr:    
    runs-on: ubuntu-latest    
  steps:      
    - uses: actions/checkout@v2      
    - uses: actions/setup-node@v2        
      with:          
        node-version: 14          
        registry-url: https://npm.pkg.github.com/
    - name: Install packages 
      run: npm install  
      working-directory: ./kodama
    - name: Pusblish to npm    
      run: npm publish     
      working-directory: ./kodama   
  env:
    NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}