name: Storybook
on:
  push:
    paths: ["src/**", "tailwind.config.js"] # Trigger the action only when files change in the folders defined here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
          cache: 'npm'

      - name: Install and Build
        run: |
          npm install
          npm run build:storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          branch: gh-pages
          folder: storybook-static # output folder from `npm run build-storybook`